#!/usr/bin/env bash

#https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
#https://stackoverflow.com/a/246128
#Dave Dopson https://stackoverflow.com/users/407731
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  dir0=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$dir0/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
dir0=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

$dir0/bin/pip3.10 "$@"
